### ISSUE TITLE
テストが正常に実行できない

### ISSUE THREAD

**Issue by aximov** [aximov/witness-me#1]
test-url ブランチで作業中、 `rails t` を実行しても以下のようなDBに関係するエラーが出てテストの成功・失敗が判定できない。正常に実行できた場合は Error ではなく Failure が表示されるか、何も表示されないはず。どうも PostgreSQL を使っていることによるエラーのように思えるが…

```
$ rails t
...
# Running:

E

Error:
TweetTest#test_should_not_save_tweet_without_URL:
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, MyString, MyText, f, f, 2020-04-19 13:25:52.401574, 2020-04-19 13:25:52.401574).

    


rails test test/models/tweet_test.rb:4

E

Error:
HomeControllerTest#test_should_get_index:
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, MyString, MyText, f, f, 2020-04-19 13:25:52.412482, 2020-04-19 13:25:52.412482).

    


rails test test/controllers/home_controller_test.rb:4



Finished in 0.028720s, 69.6385 runs/s, 0.0000 assertions/s.
2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
```

**Comment by aximov** [comment]
解決。 test/fixtures/tweets.yml が

```yml
one:
  id:
  url: MyString
  content: MyText
  is_ACNH: false
  contain_image: false
```

となっていたが、これは tweet モデルを generate したときに誤って id カラムも生成してしまったため（のち削除）で、以下のように id カラムを削除すればテストが正常に動作するようになった。

```yml
one:
  url: MyString
  content: MyText
  is_ACNH: false
  contain_image: false
```
